import type { Metadata } from "next";
import { Geist, Geist_Mono,Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "../context/AuthContext";
import CustomNavbar  from "../components/navbars/CustomNavbar"
import { ThemeProvider } from "../components/ThemeProvider";
import Footer from "../components/Footer";

const inter = Inter({ subsets: ["latin"] });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Portföyüm",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body
        className={`${inter.className} 
        bg-gradient-to-br from-slate-50 via-gray-100 to-stone-200 
        dark:from-slate-900 dark:via-gray-900 dark:to-neutral-950 
        min-h-screen flex flex-col transition-colors duration-300`}
      >
        <ThemeProvider
          attribute="class" // Tailwind ile kullanmak için 'class' attribute'unu kullan
          defaultTheme="dark" // Varsayılan tema dark olsun
          enableSystem
          disableTransitionOnChange
        >
        <AuthProvider>
        <CustomNavbar />
          <main className="container mx-auto px-4 pt-28 md:pt-32">
              {children}
          </main>
          <Footer/>
        </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
